### PR TITLE
Migrate to paho-mqtt 2.0

### LINKED ISSUE #279: Make aiomqtt compatible with paho v2
We could use `paho.mqtt.__version__` to determine at runtime whether to pass `mqtt.CallbackAPIVersion.VERSION1` to the init call to the paho client.
```python
if mqtt.__version__.startswith("2"):
    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
else:
   client = mqtt.Client()
```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Fix #279
The tests are passing.
The typing need more work both in aiomqtt and in paho-mqtt upstream.

### CODE REVIEW

**Comment by JonathanPlasse** [comment]
@empicano, @frederikaalund, this is ready for review.
I fixed all MyPy errors and opened a pull request on paho.mqtt.python to upstream the type annotations fixes.
- eclipse/paho.mqtt.python#828

The commit `fix: MyPy errors` 8c72a1ae5cba421df4eda2507a0157c97dd32c0a, use this branch and pass the checks and tests.
The last commit `refactor: use paho-mqtt v2.0.0 with type ignores` 93014c141ea6cd6c371b071fed3a527bb9cca312, use paho-mqtt v2.0.0 with type ignores.

Thus, we can merge this PR and close #279.
And once paho-mqtt integrates eclipse/paho.mqtt.python#828, we can remove the type ignores.
In the future, we could also migrate to the new callback API.

**Review by empicano — APPROVED** [review]
I don't have any comments, LGTM, good job 😎

**Comment by frederikaalund** [comment]
Well done with this migration! 👍 I looked through the code and it looks good to me too. :) I like that you found some typing fixes for paho-mqtt as well.

**Comment by JonathanPlasse** [comment]
Thank you.

**Comment by JonathanPlasse** [comment]
Should we cut a release for this?

**Comment by frederikaalund** [comment]
> Should we cut a release for this?

Yeah, that is a good idea. 👍 We have to mention that we no longer support paho-mqtt 1.x in that one as well.

I'm currently reviewing the #287, can you do a release? :)

**Comment by JonathanPlasse** [comment]
I can do this at noon.

**Pull request merged**
